package entities.requests;
/**
 * Describes the types of possible requests that can occur in the system
 */
public enum RequestType {
	READ_ORDER, WRITE_ORDER, UPDATE_GUESTS, UPDATE_DATE, LOGIN_REQUEST,REGISTER_REQUEST,READ_EMAIL, CANCEL_REQUEST,
    GET_TAKEN_SLOTS,ORDER_NUMBER, CHECK_AVAILABLE, RESERVE_TABLE,JOIN_WAITLIST, UPDATE_DETAILS, ORDER_HISTORY,
    GET_ALL_ACTIVE_ORDERS, GET_ALL_SUBSCRIBERS, TRY_SEAT,CHECK_CONFCODE, GET_TABLE, LEAVE_TABLE, WRITE_HOURS_DATE, CHANGE_HOURS_DAY,
    GET_ALL_TABLES,ADD_TABLE, REMOVE_TABLE, UPDATE_TABLE_CAPACITY, GET_LIVE_BISTRO_STATE, GET_HOURS_DATE, GET_HOURS_DAY, ALTER_WAITLIST, LEAVE_WAITLIST, SPOT_WAITLIST,GET_MAX_TABLE, GET_REPORTS

}
